# https://hub.docker.com/r/linuxserver/heimdall
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.mattiacampagna.com`)"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      # Uses the Host rule to define which certificate to issue
      - "traefik.http.routers.heimdall.tls.certresolver=myresolver"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true