# https://hub.docker.com/r/linuxserver/plex
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      # - PLEX_CLAIM= #optional
    volumes:
      - ./library:/config
      - ./tvseries:/tv
      - ./movies:/movies
      # - ../transmission/.downloads:/downloads
    restart: unless-stopped