version: "3.6"

services:
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - 9001:80
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ../shared:/srv
      - ./filebrowser.db:/database/filebrowser.db
