version: "3"

services:
  filebrowser:
    image: filebrowser/filebrowser
    # ports:
    #   - 9001:80
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ../shared:/srv
      - ./database:/database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`files.mattiacampagna.com`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      # Uses the Host rule to define which certificate to issue
      - "traefik.http.routers.filebrowser.tls.certresolver=myresolver"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
