version: '3.9'
services:
  handbrake:
    image: jlesage/handbrake
    env_file: ../env-files/.handbrake
    volumes:
      # This is where the application stores its configuration, states, log and any files needing persistency.
      - "./config:/config"
      # This location contains files from your host that need to be accessible to the application.
      - "/home/mattia:/storage:ro"
      # This is where videos to be automatically converted are located
      - "./watch:/watch"
      # This is where automatically converted video files are written
      - "./output:/output"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.handbrake.rule=Host(`handbrake.mattiacampagna.com`)"
      - "traefik.http.routers.handbrake.entrypoints=websecure"
      # Uses the Host rule to define which certificate to issue
      - "traefik.http.routers.handbrake.tls.certresolver=myresolver"
      - "traefik.http.services.handbrake.loadbalancer.server.port=5800"
    networks:
      - traefik

networks:
  traefik:
    external: true