version: "3"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    restart: unless-stopped
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
    ports:
      - 8123:8123 #optional
    # devices:
    #   - /path/to/device:/path/to/device #optional
