version: "3"

services:
  traefik:
    container_name: traefik
    image: traefik:alpine
    restart: always
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme/acme.json:/acme.json

networks:
  traefik:
    external: true