version: "3"

services:
  nextcloud:
    image: nextcloud
    hostname: cloud.yourdomain.tld
    restart: always
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: folletto
      MYSQL_HOST: db
    networks:
      - traefik
      - dbnet
    ports:
      - "8081:80"
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:cloud.your-domain.tld
      - traefik.docker.network=traefik_srv
      - traefik.frontend.entryPoints=https
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.referrerPolicy=no-referrer

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    networks:
      - dbnet
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=folletto
      - MYSQL_PASSWORD=folletto
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

volumes:
   nextcloud:
   db:

networks:
  traefik:
    external: true
  dbnet: