version: "3"

services:
  nextcloud:
    image: nextcloud
    hostname: cloud.mattiacampagna.com
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: folletto
      MYSQL_HOST: db
      OVERWRITEPROTOCOL: https
      TRUSTED_PROXIES: 172.17.0.0/16
      OVERWRITEHOST: cloud.mattiacampagna.com
    networks:
      - traefik
      - dbnet
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.mattiacampagna.com`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      # Uses the Host rule to define which certificate to issue
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
      # Use the HSTS middleware (reference: https://docs.nextcloud.com/server/25/admin_manual/configuration_server/reverse_proxy_configuration.html)
      - "traefik.http.middlewares.hstsHeader.headers.stsSeconds=15552000"
      - "traefik.http.middlewares.hstsHeader.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.hstsHeader.headers.stsPreload=true"
      - "traefik.http.middlewares.hstsHeader.headers.forceSTSHeader=true"
      # Caldav regex (reference)
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex='https://(.*)/.well-known/(?:card|cal)dav'"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement='https://$${1}/remote.php/dav'"
      - "traefik.http.routers.nextcloud.middlewares=hstsHeader,nextcloud_redirectregex"

      - docker-volume-backup.stop-during-backup=true

  nextcloud-cron:
    image: nextcloud
    hostname: cloud.mattiacampagna.com
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: folletto
      MYSQL_HOST: db
      OVERWRITEPROTOCOL: https
      TRUSTED_PROXIES: 172.17.0.0/16
      OVERWRITEHOST: cloud.mattiacampagna.com
    entrypoint: /cron.sh
    networks:
      - traefik
      - dbnet
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    networks:
      - dbnet
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=folletto
      - MYSQL_PASSWORD=folletto
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    labels: 
      - docker-volume-backup.stop-during-backup=true

  collabora-code:
    image: collabora/code
    networks:
      - dbnet
      - traefik
    environment:
      extra_params: "--o:ssl.enable=false  --o:ssl.termination=true"
      server_name: collabora.mattiacampagna.com
      domain: mattiacampagna\.com
    extra_hosts:
      - "cloud.mattiacampagna.com:217.198.137.152"
      - "collabora.mattiacampagna.com:217.198.137.152"    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora.rule=Host(`collabora.mattiacampagna.com`)"
      - "traefik.http.routers.collabora.entrypoints=websecure"
      # Uses the Host rule to define which certificate to issue
      - "traefik.http.routers.collabora.tls.certresolver=myresolver"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"
      - "traefik.docker.network=traefik"

  # backup:
  #   image: offen/docker-volume-backup
  #   restart: unless-stopped
  #   environment:
  #     PUID: 1000
  #     PGID: 1000
  #     BACKUP_CRON_EXPRESSION: "*/1 * * * *"
  #     NOTIFICATION_LEVEL: "info"
  #     NOTIFICATION_URLS: telegram://6141937258:AAEFQ3YXIkWl-bLKl1sNgtGI2JfDsgdEJtE@telegram?chats=527653323&preview=No
  #     SSH_HOST_NAME: "192.168.0.120"
  #     SSH_USER: "servtel"
  #     SSH_PASSWORD: "webprovvisoriocom"
  #     SSH_REMOTE_PATH: "/home/servtel/my-home/nextcloud/backup"
  #   volumes:
  #     - nextcloud:/backup/nextcloud-backup:ro
  #     - db:/backup/db-backup:ro
  #     - ./notifications:/etc/dockervolumebackup/notifications.d/
  #     - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
   nextcloud:
   db:

networks:
  traefik:
    external: true
  dbnet: