version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../env-files/.immich
    #ports:
      #- 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    labels:
      # Inform Traefik to expose this service
      - "traefik.enable=true"
      # Match rule for this service
      - "traefik.http.routers.immich.rule=Host(`photos.mattiacampagna.com`)"
      # Specify that this service must be reachable only from websecure entrypoint (https)
      - "traefik.http.routers.immich.entrypoints=websecure"
      # Uses the Host rule to define which certificate to issue
      - "traefik.http.routers.immich.tls.certresolver=myresolver"
      # Internal container port
      - "traefik.http.services.immich.loadbalancer.server.port=3001"

    networks:
      - traefik
      - dbnet

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../env-files/.immich
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - dbnet

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - ../env-files/.immich
    restart: always
    networks:
      - dbnet

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always
    networks:
      - dbnet

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - ../env-files/.immich
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - dbnet

volumes:
  pgdata:
  model-cache:

networks:
  traefik:
    external: true
  dbnet: