# https://hub.docker.com/r/linuxserver/jellyfin
version: "3"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ./config:/config
      - ../shared/tvseries:/data/tvshows
      - ../shared/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
