
# https://hub.docker.com/r/linuxserver/transmission

version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - USER=mattia #optional
      - PASS=folletto #optional
    volumes:
      - .data:/config
      - ../shared:/downloads 
      - .watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`torrent.mattiacampagna.com`)"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      # Uses the Host rule to define which certificate to issue
      - "traefik.http.routers.transmission.tls.certresolver=myresolver"
    networks:
      - traefik

networks:
  traefik:
    external: true